title: Opération Manticore
description: Cours BDD NoSQL — Graph + Spatial | PostGIS + pgRouting + Neo4j
theme: just-the-docs
url: "https://mzellou.github.io"
baseurl: "/cours-manticore"

collections:
  docs:
    output: true
    permalink: /:path/

just_the_docs:
  collections:
    docs:
      nav_exclude: false

color_scheme: dark
